"""
Comprehensive 2026 Japan salary benchmarks across 11 industry sectors.

Each row is a (subcategory, role_title, years_min, years_max, perm_min_M, perm_max_M,
contract_min_per_hour, contract_max_per_hour) tuple.

Salaries in millions of JPY annual; contract rates in JPY per hour.
None = not disclosed for that field.

East = Kanto (Tokyo region). West = Kansai (Osaka region).
"""

# ===========================================================================
# Market-wide 2026 outlook
# ===========================================================================

MARKET_OUTLOOK_2026 = {
    "union_settlement_2025_pct": 5.4,
    "companies_planning_raises_pct": 55,
    "ai_daily_use_2025_pct": 60.7,
    "ai_daily_use_2024_pct": 24.5,
    "foreign_workers_2024_millions": 2.3,
    "foreign_residents_2025_millions": 3.8,
    "top_skills_employers_want": [
        "Data analysis and interpretation",
        "Critical thinking and problem-solving",
        "Human-AI collaboration skills",
    ],
}


# ===========================================================================
# Per-sector data
# ===========================================================================

SECTORS: list[dict] = [

    # ========================================================================
    {
        "slug": "accounting-finance",
        "icon": "chart-bar",
        "name": "Accounting & Finance",
        "salary_increase_pct": 57,
        "confidence_pct": 62,
        "mobility_pct": 44,
        "expected_pay_bump_low": 5,
        "expected_pay_bump_high": 15,
        "expected_pay_bump_note": "Job changers see 5% in cautious cases; 8–10% expected by qualified professionals; up to 15% for bilingual M&A / strategy talent.",
        "top_demand": [
            "Financial Planning & Analysis / Strategy",
            "Financial Manager / Controller",
            "Accounting Manager",
        ],
        "trend_summary": "Hiring freezes and budget constraints have intensified competition for permanent hires, with companies relying more on contract talent. Demand stays strong for FP&A, treasury, tax compliance, transfer pricing, and IFRS expertise. Bilingual mid-career professionals with M&A and corporate strategy experience are seeing robust opportunities.",
        "trend_east": "Companies in East Japan are responding to hiring freezes with greater reliance on senior contractors. FP&A, treasury, transfer pricing, and IFRS expertise top the demand list. Bilingual mid-career professionals with M&A and change-management experience are positioned to drive premium offers.",
        "trend_west": "Kansai's accounting/finance hiring is steady thanks to a stable manufacturing base (automotive, pharma, chemical). Growing demand for M&A, IR, financial planning, and senior accounting in hospitality. Many U-turn candidates (returning from Tokyo) are filling roles.",
        "roles_east": [
            ("Accounting", "AP/AR Staff", 2, None, 5, 7, 1800, 2500),
            ("Accounting", "Cost Accountant", 3, None, 9, 11, None, None),
            ("Accounting", "Credit Manager", 5, None, 9, 12, None, None),
            ("Accounting", "Financial Accountant", 3, None, 8, 10, 2000, 3000),
            ("Accounting", "Financial Accounting Manager", 6, None, 10, 15, 2800, 4000),
            ("Accounting", "Internal Audit Manager", 6, None, 11, 18, None, None),
            ("Accounting", "Internal Auditor", 3, None, 8, 13, None, None),
            ("Accounting", "Senior Financial Accountant", 4, None, 8, 11, 2500, 3500),
            ("Accounting", "Tax Accountant", 4, None, 9, 12, 2200, 3200),
            ("Accounting", "Tax Manager", 6, None, 13, 18, 3000, 4500),
            ("Accounting", "Treasury Accountant", 3, None, 8, 10, None, None),
            ("Accounting", "Treasury Manager", 6, None, 11, 15, None, None),
            ("Financial Planning & Analysis", "Business Controller", 5, None, 10, 18, None, None),
            ("Financial Planning & Analysis", "Financial Analyst", 3, None, 8, 12, 2500, 3200),
            ("Financial Planning & Analysis", "Financial Planning Manager", 6, None, 12, 18, 3500, 5000),
            ("Financial Planning & Analysis", "Senior Financial Analyst", 4, None, 10, 14, None, None),
            ("Large Organisation", "Chief Financial Officer", 15, None, 30, 70, None, None),
            ("Large Organisation", "Financial Controller", 8, None, 15, 25, 4000, 7500),
            ("SME", "Chief Financial Officer", 10, None, 15, 30, 3500, 7000),
            ("SME", "Financial Controller", 10, None, 14, 18, 3500, 6000),
        ],
        "roles_west": [
            ("General", "Chief Financial Officer", 10, 20, 12, 30, None, None),
            ("General", "Finance Director", 10, 20, 15, 25, None, None),
            ("General", "Financial Controller", 8, 15, 10, 18, 2900, 5000),
            ("General", "Finance Manager", 5, 10, 8, 12, 2100, 4800),
            ("General", "FP&A Director", 10, 20, 13, 18, None, None),
            ("General", "FP&A Manager", 8, 12, 10, 15, None, None),
            ("General", "Financial Accounting Manager", 7, 12, 8, 12, 2200, 4800),
            ("General", "Internal Audit Manager", 5, 10, 10, 15, None, None),
            ("General", "Tax Manager", 5, 10, 8, 15, None, None),
            ("General", "Treasury Manager", 7, 12, 8, 12, None, None),
            ("General", "Financial Analyst", 5, 10, 6, 8, 1700, 3900),
            ("General", "Senior Financial Accountant", 5, 8, 7, 9, 1800, 3500),
            ("General", "Tax Accountant", 5, 8, 6, 9, 1800, 3100),
            ("General", "Internal Auditor", 5, 8, 6, 9, None, None),
            ("General", "Cost Accountant", 5, 10, 7, 10, None, None),
            ("General", "Financial Accountant", 5, 10, 5, 7, 1400, 2500),
            ("General", "AP/AR Staff", 5, 7, 4.5, 7, 1400, 2500),
        ],
    },

    # ========================================================================
    {
        "slug": "banking-financial-consulting",
        "icon": "building",
        "name": "Banking, Financial Services & Consulting",
        "salary_increase_pct": 51,
        "confidence_pct": 68,
        "mobility_pct": 44,
        "expected_pay_bump_low": 7,
        "expected_pay_bump_high": 20,
        "expected_pay_bump_note": "7–12% standard for banking job changers; 5–10% in temp/support functions; up to 20% for skilled PE/M&A talent and partner-level consultants.",
        "top_demand": [
            "PE / Alternatives (Analysts / Associates)",
            "Operations (Senior Associate / AVP level)",
            "M&A Advisory",
        ],
        "trend_summary": "The weak yen has made Japan attractive to foreign investors, driving expansion among alternative investment firms. Investment banks plan to grow teams in 2026, especially PE, M&A advisory, IR, and compliance. Real-estate asset management and acquisition professionals are also in high demand.",
        "trend_east": "Banking and financial services continue to face a shortage of junior and mid-career talent. Companies are focusing on hiring senior candidates. Consulting demand is strong for mid-to-senior professionals with post-merger integration (PMI) and Value-Up expertise. CPA-qualified consultants with 5+ years command competitive offers; partner roles offer exceptional compensation due to talent shortages.",
        "roles_east": [
            ("General", "Internal Audit (0-4y)", 0, 4, 7, 9, None, None),
            ("General", "Internal Audit (4-8y)", 4, 8, 10, 12, None, None),
            ("General", "Internal Audit (8-15y)", 8, 15, 11, 22, None, None),
            ("General", "Sales (0-4y)", 0, 4, 8, 10.5, None, None),
            ("General", "Sales (4-8y)", 4, 8, 9, 15, None, None),
            ("General", "Sales (8-15y)", 8, 15, 15, 27, None, None),
            ("General", "Middle Office (0-3y)", 0, 3, 7, 9, None, None),
            ("General", "Middle Office (4-8y)", 4, 8, 8.5, 13, None, None),
            ("General", "Middle Office (8-15y)", 8, 15, 12, 20, None, None),
            ("General", "Settlements (0-3y)", 0, 3, 7, 9, None, None),
            ("General", "Settlements (4-8y)", 4, 8, 8.5, 13, None, None),
            ("General", "Settlements (8-15y)", 8, 15, 12, 20, None, None),
            ("General", "Product Management (0-4y)", 0, 4, 8, 10.5, None, None),
            ("General", "Product Management (4-8y)", 4, 8, 8.5, 13, None, None),
            ("General", "Product Management (8-15y)", 8, 15, 12, 25, None, None),
            ("General", "Project Management (0-4y)", 0, 4, 7, 10.5, None, None),
            ("General", "Project Management (4-8y)", 4, 8, 8.5, 13, None, None),
            ("General", "Project Management (8-15y)", 8, 15, 12, 25, None, None),
            ("General", "Marketing Manager", None, None, 10, 15, 3800, 8100),
            ("General", "Marketing Director", None, None, 15, 25, 5100, 12000),
            ("Assurance", "Consultant (1-5y)", 1, 5, 4, 8, None, None),
            ("Assurance", "Consultant (6-10y)", 6, 10, 8, 14, None, None),
            ("Assurance", "Consultant (11-25y)", 11, 25, 15, 30, None, None),
            ("M&A Advisory (FAS)", "Consultant (2-5y)", 2, 5, 6, 12, None, None),
            ("M&A Advisory (FAS)", "Consultant (6-10y)", 6, 10, 12, 18, None, None),
            ("M&A Advisory (FAS)", "Consultant (11-25y)", 11, 25, 20, 50, None, None),
            ("Management Consulting", "Consultant (2-5y)", 2, 5, 5, 8, None, None),
            ("Management Consulting", "Consultant (6-10y)", 6, 10, 10, 16, None, None),
            ("Management Consulting", "Consultant (11-25y)", 11, 25, 20, 35, None, None),
            ("Strategy Consulting", "Consultant (2-5y)", 2, 5, 7, 15, None, None),
            ("Strategy Consulting", "Consultant (6-10y)", 6, 10, 15, 22, None, None),
            ("Strategy Consulting", "Consultant (11-25y)", 11, 25, 20, 50, None, None),
            ("Tax", "Consultant (1-5y)", 1, 5, 4, 8, None, None),
            ("Tax", "Consultant (6-10y)", 6, 10, 8, 14, None, None),
            ("Tax", "Consultant (11-25y)", 11, 25, 15, 30, None, None),
            ("Real Estate / Asset Mgmt", "Real Estate Asset Management (0-4y)", 0, 4, 7, 10, None, None),
            ("Real Estate / Asset Mgmt", "Real Estate Asset Management (4-8y)", 4, 8, 8.5, 13, None, None),
            ("Real Estate / Asset Mgmt", "Real Estate Asset Management (8-15y)", 8, 15, 12, 21, None, None),
            ("Real Estate / Asset Mgmt", "Sales Manager / Business Development Manager", None, None, 7, 10, 3800, 8100),
            ("Real Estate / Asset Mgmt", "Sales Director / Business Development Director", None, None, 12, 20, 5100, 12000),
        ],
    },

    # ========================================================================
    {
        "slug": "consumer-goods-hospitality-retail",
        "icon": "gift",
        "name": "Consumer Goods, Hospitality & Retail",
        "salary_increase_pct": 56,
        "confidence_pct": 65,
        "mobility_pct": 52,
        "expected_pay_bump_low": 15,
        "expected_pay_bump_high": 20,
        "expected_pay_bump_note": "Employers typically need to offer 15%+ to attract top talent; up to 20% for in-demand brand and BD profiles. Kansai averaged 5–10% in 2025 due to oversupply.",
        "top_demand": [
            "Brand Marketing — Senior Manager / Director",
            "Client Engagement / Business Development — Senior Manager / Director",
            "General Manager",
        ],
        "trend_summary": "Inflation continues to squeeze B2C margins; consumers prefer high-quality mid-priced products and experiences over luxury. Marketing roles are critically understaffed. Hospitality and retail are prioritising re-engaging 'boomerang employees' and offering competitive packages. Skilled candidates hold significant leverage.",
        "trend_east": "Marketing roles are critically understaffed; companies seek professionals who can differentiate brands beyond pricing. Business development with client-facing skills is in strong demand. Country managers with Japan-specific go-to-market strategies are highly sought after. Burnout and work-life balance are top concerns for candidates.",
        "trend_west": "Post-Osaka Expo, ~20,000 temporary workers returned to the labour market. Luxury retail recruitment is slow due to reduced Chinese inbound tourism. Strong demand for VIP-focused sales pros, BD specialists, and CX talent who can add empathy where AI falls short. U-turn job seekers returning to Kansai are increasingly attractive to employers.",
        "roles_east": [
            ("Consumer/FMCG", "President / Country Manager", None, None, 20, 35, 6500, 14000),
            ("Consumer/FMCG", "Commercial Director", None, None, 15, 25, 5100, 12000),
            ("Consumer/FMCG", "Commercial Manager", None, None, 10, 15, 3800, 8100),
            ("Consumer/FMCG", "Sales Director", None, None, 15, 25, 5100, 12000),
            ("Consumer/FMCG", "Sales Manager", None, None, 10, 15, 3800, 8100),
            ("Consumer/FMCG", "Key Account Manager", None, None, 8, 12, 3800, 8100),
            ("Consumer/FMCG", "Sales Representative / Specialist", None, None, 5, 8, 2500, 5100),
            ("Consumer/FMCG", "Marketing Director", None, None, 15, 25, 5100, 12000),
            ("Consumer/FMCG", "Marketing Manager", None, None, 10, 15, 3800, 8100),
            ("Consumer/FMCG", "Consumer Insights Manager", None, None, 8, 12, 3800, 8100),
            ("Consumer/FMCG", "Trade Marketing Manager", None, None, 8, 12, 3800, 8100),
            ("Consumer/FMCG", "Trade Marketing Specialist", None, None, 5, 7, 2500, 5100),
            ("Consumer/FMCG", "Senior Brand Manager", None, None, 10, 12, 3800, 8100),
            ("Consumer/FMCG", "Brand / Product Manager", None, None, 8, 12, 3800, 8100),
            ("Consumer/FMCG", "Assistant Brand Manager", None, None, 6, 8, 3800, 8100),
            ("Consumer/FMCG", "Brand Specialist", None, None, 4, 6, 2500, 5100),
            ("Consumer/FMCG", "Brand Communications Manager", None, None, 10, 14, 3800, 8100),
            ("Consumer/FMCG", "PR / Corporate Communications Director", None, None, 15, 20, 5100, 12000),
            ("Consumer/FMCG", "PR / Corporate Communications Manager", None, None, 10, 12, 3800, 8100),
            ("Consumer/FMCG", "PR Staff", None, None, 4, 6, 2500, 5100),
            ("Consumer/FMCG", "Content Creation Manager", None, None, 8, 12, 3800, 8100),
            ("Consumer/FMCG", "Content Creation Specialist", None, None, 6, 8, 2500, 5100),
            ("Consumer/FMCG", "Copywriter", None, None, 4, 6, 2500, 5100),
            ("Hospitality", "General Manager", None, None, 15, 25, None, None),
            ("Hospitality", "Hotel Manager / Executive Assistant Manager", None, None, 13, 18, None, None),
            ("Hospitality", "Director", None, None, 8, 15, None, None),
            ("Hospitality", "Senior Manager / Manager", None, None, 5, 7, None, None),
            ("Hospitality", "Executive / Coordinator", None, None, 3, 4, None, None),
            ("Retail", "General Manager", None, None, 18, 50, 6500, 14000),
            ("Retail", "Retail Director", None, None, 15, 28, 5100, 12000),
            ("Retail", "Retail Manager", None, None, 10, 14, 3800, 8100),
            ("Retail", "Area Manager", None, None, 5, 8, 3800, 8100),
            ("Retail", "Retail Operations Manager", None, None, 10, 14, 3800, 8100),
            ("Retail", "Retail Operations Specialist", None, None, 6, 9, 2500, 5100),
            ("Retail", "Merchandising Director", None, None, 13, 28, 5100, 12000),
            ("Retail", "Merchandising Manager", None, None, 10, 13, 3800, 8100),
            ("Retail", "Merchandising Specialist", None, None, 5, 8, 2500, 5100),
            ("Retail", "PR Director", None, None, 15, 20, 5100, 12000),
            ("Retail", "PR Manager", None, None, 8, 14, 3800, 8100),
            ("Retail", "PR Specialist", None, None, 5, 7, 3800, 8100),
            ("Retail", "Brand Marketing Director", None, None, 15, 25, 5100, 12000),
            ("Retail", "Brand Marketing Manager", None, None, 11, 14, 3800, 8100),
            ("Retail", "Marketing Director", None, None, 15, 36, 5100, 12000),
            ("Retail", "Marketing Manager", None, None, 10, 14, 3800, 8100),
            ("Retail", "Marketing Specialist", None, None, 5, 8, 2500, 5100),
            ("Retail", "CRM Director", None, None, 15, 25, 5100, 12000),
            ("Retail", "CRM Manager", None, None, 10, 14, 3800, 8100),
            ("Retail", "CRM Specialist", None, None, 7, 9, 2500, 5100),
            ("Retail", "VIP / Clienteling Manager", None, None, 10, 14, 3800, 8100),
            ("Retail", "VIP / Clienteling Specialist", None, None, 5, 8, 2500, 5100),
            ("Retail", "Gaisho Specialist (外商)", None, None, 5, 12, 3800, 8100),
            ("Retail", "Store Manager", None, None, 5, 12, 3800, 8100),
            ("Retail", "Assistant Store Manager", None, None, 6, 8, 3800, 8100),
            ("Retail", "Store Staff", None, None, 4, 6, 2500, 5100),
            ("Retail", "Visual Merchandising Manager", None, None, 8, 10, 3800, 8100),
            ("Retail", "Visual Merchandising Specialist", None, None, 6, 8, 3800, 8100),
            ("Retail", "Travel Retail Director", None, None, 15, 25, 5100, 12000),
            ("Retail", "Travel Retail Manager", None, None, 10, 14, 3800, 8100),
            ("Retail", "Store Development Director", None, None, 12, 20, 5100, 12000),
            ("Retail", "Store Development Manager", None, None, 10, 12, 3800, 8100),
            ("Retail", "Store Expansion Director", None, None, 12, 25, 5100, 12000),
            ("Retail", "Store Expansion Manager", None, None, 10, 12, 3800, 8100),
        ],
        "roles_west": [
            ("Consumer/FMCG", "Marketing Executive", None, None, 5, 9, None, None),
            ("Consumer/FMCG", "Sales Executive", None, None, 5, 8.5, 1500, 2500),
        ],
    },

    # ========================================================================
    {
        "slug": "consumer-corporate-services",
        "icon": "megaphone",
        "name": "Consumer & Corporate Services",
        "salary_increase_pct": 53,
        "confidence_pct": 65,
        "mobility_pct": 46,
        "expected_pay_bump_low": 10,
        "expected_pay_bump_high": 20,
        "expected_pay_bump_note": "10–15% for job changers across the board; up to 20% in asset management. Beyond salary, candidates expect meaningful responsibilities and DEI / mental health benefits.",
        "top_demand": [
            "Business Development / Sales Manager",
            "Corporate Communication",
            "PR Consultant (Account Manager / Director)",
        ],
        "trend_summary": "AI is reshaping marketing and communications; digital fluency is now table stakes. Demand is surging for globally minded English-speaking professionals supporting Japanese entertainment exports (music, anime, gaming). Japanese fluency remains strict for B2B and corporate comms, but companies are flexing on industry experience.",
        "trend_east": "Marketing and communications now demand digital and AI fluency alongside creative problem-solving. Demand is high for globally-minded, English-proficient professionals supporting Japanese entertainment exports. Bilingual professionals remain critical for corporate communications and B2B roles. Remote work options are decisive in retention.",
        "roles_east": [
            ("Banking / Asset Management / IB", "Corporate Communication Manager", None, None, 12, 15, 5100, 12000),
            ("Banking / Asset Management / IB", "Corporate Communication Director", None, None, 15, 25, 3800, 8100),
            ("Corporate Education", "Marketing Manager", None, None, 8, 10, 3800, 8100),
            ("Corporate Education", "Marketing Director", None, None, 10, 15, 5100, 12000),
            ("Financial Services", "Marketing Manager / Communication Manager", None, None, 10, 15, 3800, 8100),
            ("Financial Services", "Marketing Director / Communication Director", None, None, 15, 25, 5100, 12000),
            ("Insurance / Entertainment / Consulting", "Marketing Manager", None, None, 8, 12, 3800, 8100),
            ("Insurance / Entertainment / Consulting", "Marketing Director", None, None, 13, 18, 5100, 12000),
            ("Insurance / Real Estate / Service", "Corporate Communication Manager", None, None, 8, 11, 3800, 8100),
            ("Insurance / Real Estate / Service", "Corporate Communication Director", None, None, 13, 18, 5100, 12000),
            ("Marketing Research Agency", "Research / Sales Manager", None, None, 7, 10, 3800, 8100),
            ("Marketing Research Agency", "Research / Sales Director", None, None, 11, 14, 5100, 12000),
            ("PR Agency", "Manager-Level Consultant", None, None, 6, 10, 3800, 8100),
            ("PR Agency", "Director-Level Consultant", None, None, 11, 20, 5100, 12000),
            ("Record Label", "A&R Manager", None, None, 6, 12, 3800, 8100),
            ("Shared Office / Real Estate / Education", "Sales Manager / BD Manager", None, None, 7, 10, 3800, 8100),
            ("Shared Office / Real Estate / Education", "Sales Director / BD Director", None, None, 12, 20, 5100, 12000),
        ],
    },

    # ========================================================================
    {
        "slug": "hr-business-support",
        "icon": "users",
        "name": "HR & Business Support",
        "salary_increase_pct": 49,
        "confidence_pct": 55,
        "mobility_pct": 48,
        "expected_pay_bump_low": 3,
        "expected_pay_bump_high": 15,
        "expected_pay_bump_note": "HR side: 5–15% (global Japanese companies pay most). Business Support side: 3–5% — modest as AI replaces administrative work.",
        "top_demand": [
            "HR Business Partner",
            "HR Director",
            "General Affairs Manager",
        ],
        "trend_summary": "HR and business support are diverging. HR remains hot — especially at international companies — while business support is contracting as AI replaces administrative work. Bilingual real-time interpreters remain valuable as they handle nuance AI cannot.",
        "trend_east": "Demand stays high for senior HR, talent acquisition, and HRBP. Executive assistant roles are declining as AI replaces traditional functions, though older candidates (avg age 55+) are increasingly being hired for contract roles. Remote/hybrid options remain a competitive differentiator.",
        "trend_west": "Kansai HR is reshaping fast with AI handling admin tasks. Demand is rising for senior and director-level positions due to retirement-driven succession planning. Real-time interpreters in high demand; translators declining. Compensation design, HRBP, and bilingual professionals are best positioned.",
        "roles_east": [
            ("Financial Services HR", "HR Director", None, None, 16, 30, None, None),
            ("Financial Services HR", "HR Business Partner", None, None, 10, 20, None, None),
            ("Financial Services HR", "HR Generalist", 0, 6, 6, 9, 1700, 2500),
            ("Financial Services HR", "Recruitment / Staffing Manager", None, None, 8, 20, 3000, 7000),
            ("Financial Services HR", "Recruitment / Staffing Coordinator", None, None, 4.5, 9, 1700, 2500),
            ("Financial Services HR", "Learning & Development Head", None, None, 12, 18, 3000, 7000),
            ("Financial Services HR", "Training Specialist", None, None, 5, 12, 1700, 2500),
            ("Financial Services HR", "Compensation & Benefits Director", None, None, 13, 20, None, None),
            ("Financial Services HR", "Compensation & Benefits Specialist", None, None, 6, 12, 1700, 2500),
            ("Financial Services HR", "Payroll Specialist", None, None, 5, 9, 1700, 2500),
            ("Financial Services HR", "Facilities Manager", None, None, 7, 14, 2000, 3300),
            ("Financial Services Support", "Administration Manager", None, None, 6, 10, 1800, 2800),
            ("Financial Services Support", "Executive Secretary", None, None, 6, 12, 1700, 2500),
            ("Financial Services Support", "Translator / Interpreter", None, None, 5, 10, 2200, 4000),
            ("Financial Services Support", "General Affairs Administrator", None, None, 5, 8, 1700, 2500),
            ("Financial Services Support", "Office Administrator", None, None, 4.5, 6.5, 1700, 2500),
            ("Financial Services Support", "Group Secretary", None, None, 5, 7, 1700, 2500),
            ("Financial Services Support", "Receptionist", None, None, 3.6, 5.5, 1700, 2300),
            ("Non-Financial HR", "HR Director / Head", None, None, 12, 25, None, None),
            ("Non-Financial HR", "HR Generalist (6y+)", 6, None, 6, 13, 1700, 2500),
            ("Non-Financial HR", "HR Manager", None, None, 8, 18, 3000, 6000),
            ("Non-Financial HR", "HR Specialist", None, None, 5.5, 11, 1700, 2500),
            ("Non-Financial HR", "HR Administrator", None, None, 4.5, 7, 1700, 2500),
            ("Non-Financial HR", "Compensation & Benefits Manager", None, None, 8, 16, 1700, 2500),
            ("Non-Financial HR", "Recruitment / Staffing Manager", None, None, 8, 16, 3000, 7000),
            ("Non-Financial Support", "Office Manager", None, None, 8, 12, 2000, 2800),
            ("Non-Financial Support", "Administration Manager", None, None, 7, 10, 2000, 2800),
            ("Non-Financial Support", "Administrative Assistant", None, None, 5, 7, 1500, 2500),
            ("Non-Financial Support", "Executive Secretary", None, None, 6, 11, 1700, 2500),
            ("Non-Financial Support", "General Affairs Manager", None, None, 8, 13, 2000, 2800),
            ("Non-Financial Support", "General Affairs Administrator", None, None, 5, 8, 1700, 2500),
            ("Non-Financial Support", "Translator / Interpreter", None, None, 6, 10, 2200, 4000),
        ],
        "roles_west": [
            ("Financial Services", "Operations VP", 14, 19, 15, 22, 1500, 1700),
            ("Financial Services", "Operations Director", 9, 14, 10, 16, 1800, 3800),
            ("Financial Services", "Operations Associate", 7, 9, 8, 10, 1700, 3700),
            ("Financial Services", "Operations Analyst", 6, 8, 7, 9, None, None),
            ("Professional Services", "HR Director", 10, 20, 10, 23, None, None),
            ("Professional Services", "HR Business Partner", 5, 10, 7, 18, None, None),
            ("Professional Services", "HR Manager / Generalist (6y+)", 6, 10, 8, 12, 2000, 3900),
            ("Professional Services", "Senior HR Generalist", 6, 9, 6, 9, None, None),
            ("Professional Services", "HR Generalist / Staff", 3, 5, 5, 8.5, 1400, 2400),
            ("Professional Services", "Compensation & Benefits Specialist", 2, 5, 7, 10, None, None),
            ("Professional Services", "Payroll Specialist", 3, 6, 5, 10, 1400, 2400),
            ("Professional Services", "General Affairs Manager", 5, 10, 7, 15, None, None),
            ("Professional Services", "General Affairs Administrator", 3, 6, 5, 8, None, None),
            ("Professional Services", "Office Manager", 5, 10, 5, 10, None, None),
            ("Professional Services", "Administration Manager", 5, 10, 6, 9, None, None),
            ("Professional Services", "Administrative Assistant", 3, 6, 5, 7, None, None),
            ("Professional Services", "Executive Secretary", 3, 6, 5, 10, None, None),
            ("Professional Services", "Translator / Interpreter", 3, 6, 5, 10, None, None),
        ],
    },

    # ========================================================================
    {
        "slug": "healthcare",
        "icon": "support",
        "name": "Healthcare",
        "salary_increase_pct": 56,
        "confidence_pct": 66,
        "mobility_pct": 49,
        "expected_pay_bump_low": 5,
        "expected_pay_bump_high": 15,
        "expected_pay_bump_note": "Pharma: 10–15%. Medical device: 5–7%. Health services: 10–15%. Diversity hiring and hands-on experience valued for executive roles.",
        "top_demand": [
            "Marketing",
            "RA / QA (Regulatory / Quality Assurance)",
            "Business Development",
        ],
        "trend_summary": "Japan's ageing population continues driving demand across pharma, medical devices, and health services. Pharmaceutical sector picked up after restructuring. Medical device sector is expanding around age-related disease products. Health services rely increasingly on part-time and foreign workers.",
        "trend_east": "Pharma hiring picked up after restructuring. Strong demand for marketing, regulatory affairs, quality assurance, and BD. Job changers expect 10–15% gains; diversity hiring and hands-on experience prioritised for executives. Medical device sector expanding for age-related disease products at steady 5–7% increases.",
        "trend_west": "Kansai healthcare saw workforce reductions in 2025, increasing talent mobility. Strong demand for Medical Affairs specialists, Clinical Specialists, and Real-World Data experts. Many companies are implementing 'no relocation' policies and offering relocation support including company housing, sign-on bonuses, and Shinkansen commute subsidies.",
        "roles_east": [
            ("Contract Research Organisation", "CRO Clinical Development Manager", None, None, 10, 17, 3500, 7500),
            ("Contract Research Organisation", "CRO Clinical Research Associate", None, None, 6, 14, 3000, 6000),
            ("Contract Research Organisation", "Data Manager", None, None, 6, 9, 3500, 7500),
            ("Contract Research Organisation", "CRO/CMO Business Development Manager/Director", None, None, 12, 22, 4500, 11000),
            ("Contract Research Organisation", "CRO Pharmacovigilance Specialist / Manager", None, None, 7, 10, 4500, 11000),
            ("Contract Research Organisation", "CRO Regulatory Affairs Manager", None, None, 7, 12, 4500, 11000),
            ("Contract Research Organisation", "Regulatory Affairs Consulting", None, None, 8, 15, 4500, 11000),
            ("Contract Research Organisation", "CSO MSL / Medical Affairs", None, None, 7, 10, 3500, 7500),
            ("Healthcare Agency", "Healthcare Marketing Research", None, None, 6, 9, 3500, 7500),
            ("Healthcare Agency", "Healthcare Account Manager / Executive / Sales", None, None, 7, 15, 3500, 7500),
            ("Healthcare Agency", "Healthcare PR / Medical Communication", None, None, 5, 13, 3500, 7500),
            ("Healthcare Consulting", "Healthcare Consulting", None, None, 8, 18, 4500, 11000),
            ("Healthcare Consulting", "RWE / Epidemiology", None, None, 8, 15, 4500, 11000),
            ("Medical Device / Life Science", "Commercial Excellence Director", None, None, 14, 20, 5100, 12000),
            ("Medical Device / Life Science", "Commercial Excellence Manager", None, None, 12, 17, 4500, 11000),
            ("Medical Device / Life Science", "Commercial Excellence Specialist", None, None, 7, 12, 3500, 7500),
            ("Medical Device / Life Science", "PR / Communication Director", None, None, 14, 22, 5100, 12000),
            ("Medical Device / Life Science", "PR / Communication Manager", None, None, 12, 16, 4500, 11000),
            ("Medical Device / Life Science", "PR / Communication Specialist", None, None, 5, 9, 3500, 7500),
            ("Medical Device / Life Science", "Clinical Director", None, None, 14, 22, 5100, 12000),
            ("Medical Device / Life Science", "Clinical Manager", None, None, 10, 15, 4500, 11000),
            ("Medical Device / Life Science", "Clinical Research Associate (CRA)", None, None, 5, 9, 3500, 7500),
            ("Medical Device / Life Science", "Business Development Director", None, None, 14, 22, 5100, 12000),
            ("Medical Device / Life Science", "Business Development Manager", None, None, 12, 17, 4500, 11000),
            ("Medical Device / Life Science", "Business Development Specialist", None, None, 7, 12, 3500, 7500),
            ("Pharmaceutical", "President / Country Manager", None, None, 25, 40, 6800, 16000),
            ("Pharmaceutical", "Business Unit Head", None, None, 20, 30, 5700, 14000),
            ("Pharmaceutical", "Marketing Director", None, None, 16, 24, 5100, 12000),
            ("Pharmaceutical", "Marketing Manager", None, None, 14, 19, 4500, 11000),
            ("Pharmaceutical", "Product Manager", None, None, 10, 15, 3500, 7500),
            ("Pharmaceutical", "Corporate Strategy / Business Strategy", None, None, 12, 25, 5100, 12000),
            ("Pharmaceutical", "Commercial Excellence Director", None, None, 18, 25, 5100, 12000),
            ("Pharmaceutical", "Commercial Excellence Manager", None, None, 11, 16, 4500, 11000),
            ("Pharmaceutical", "Business Development Director", None, None, 15, 24, 5100, 12000),
            ("Pharmaceutical", "Business Development Manager", None, None, 10, 15, 4500, 11000),
            ("Pharmaceutical", "Governmental Affairs", None, None, 10, 20, 5100, 12000),
            ("Pharmaceutical", "Market Access / Pricing / Health Economics", None, None, 10, 25, 5100, 12000),
            ("Pharmaceutical", "Medical Affairs Director", None, None, 20, 30, 5100, 12000),
            ("Pharmaceutical", "Medical Affairs Manager", None, None, 13, 19, 4500, 11000),
            ("Pharmaceutical", "Medical Affairs Specialist", None, None, 8, 14, 3500, 7500),
            ("Pharmaceutical", "RA / QA Head", None, None, 20, 30, 5700, 14000),
            ("Pharmaceutical", "Regulatory Affairs Manager", None, None, 12, 19, 4500, 11000),
            ("Pharmaceutical", "Regulatory Affairs Specialist", None, None, 8, 14, 3500, 7500),
            ("Pharmaceutical", "Quality Assurance Manager", None, None, 10, 15, 4500, 11000),
            ("Pharmaceutical", "Quality Assurance Specialist", None, None, 7, 12, 3500, 7500),
            ("Pharmaceutical", "Pharmacovigilance Manager", None, None, 10, 16, 4500, 11000),
            ("Pharmaceutical", "Pharmacovigilance Specialist", None, None, 7, 11, 3500, 7500),
            ("Pharmaceutical", "Data Management / Biostatistics", None, None, 6, 14, 4500, 11000),
            ("Pharmaceutical", "Medical Writing", None, None, 7, 14, 4500, 11000),
            ("Pharmaceutical", "Clinical Director", None, None, 15, 25, 4500, 11000),
            ("Pharmaceutical", "Clinical Project Manager", None, None, 10, 16, 4500, 11000),
            ("Pharmaceutical", "Clinical Research Associate (CRA)", None, None, 6, 10, 3500, 7500),
            ("Pharmaceutical", "Medical Science Liaison", None, None, 7, 15, 4500, 11000),
            ("Pharmaceutical", "CMC Researcher", None, None, 8, 20, 4500, 11000),
            ("Pharmaceutical", "Senior Scientist", None, None, 8, 14, 4500, 11000),
            ("Pharmaceutical", "Scientist", None, None, 6, 11, 3500, 7500),
        ],
        "roles_west": [
            ("General", "General Manager / Country Manager", None, None, 18, 50, None, None),
            ("General", "Marketing Director", None, None, 12, 25, None, None),
            ("General", "Sales Manager", None, None, 12, 22, None, None),
            ("General", "Clinical Development Manager", None, None, 10, 18, None, None),
            ("General", "Regulatory Affairs Manager", None, None, 10, 20, None, None),
            ("General", "Regulatory Affairs Specialist", None, None, 8, 12, 1700, 3100),
            ("General", "Marketing / Product Manager", None, None, 8, 15, None, None),
            ("General", "Clinical Scientist / Researcher", None, None, 6, 12, None, None),
            ("General", "Clinical Research Associate (CRA)", None, None, 5.5, 10, None, None),
            ("General", "Quality Assurance Manager", None, None, 10, 16, None, None),
            ("General", "Quality Assurance", None, None, 5, 10, 1500, 2200),
            ("General", "Field Service Manager", None, None, 8, 12, None, None),
            ("General", "Field Service Engineer", None, None, 6, 9, None, None),
            ("General", "Field Application Specialist", None, None, 7, 11, None, None),
            ("General", "Sales Representative", None, None, 6, 12, None, None),
        ],
    },

    # ========================================================================
    {
        "slug": "legal-compliance-risk",
        "icon": "scale",
        "name": "Legal, Compliance & Risk",
        "salary_increase_pct": 56,
        "confidence_pct": 69,
        "mobility_pct": 41,
        "expected_pay_bump_low": 10,
        "expected_pay_bump_high": 20,
        "expected_pay_bump_note": "10–20% for legal job changers (top end for bengoshi-qualified bilinguals). 10–15% for compliance and audit, plus social insurance and pension benefits.",
        "top_demand": [
            "Legal Counsel",
            "Compliance Officer",
            "Risk Manager",
        ],
        "trend_summary": "Evolving privacy regulations and AI tools have driven demand for contract management and data governance. Tightening global regulations are increasing demand for compliance specialists at financial institutions. Bengoshi-qualified bilinguals receive multiple offers; cryptocurrency/fintech specialists are rare and highly desirable.",
        "trend_east": "Bengoshi qualifications + English proficiency is the most valuable combo — these candidates routinely receive multiple offers. Legal teams are moving from technical advisors to strategic partners, so soft skills like communication and stakeholder management matter more. Data privacy, M&A, and tech expertise particularly sought after.",
        "roles_east": [
            ("General", "Risk Officer (0-3y)", 0, 3, 6, 9, None, None),
            ("General", "Risk Officer (4-7y)", 4, 7, 9, 15, None, None),
            ("General", "Risk Officer (8-15y)", 8, 15, 12, 25, None, None),
            ("Commerce & Industry", "In-house Lawyer (0-3y)", 0, 3, 15, 20, None, None),
            ("Commerce & Industry", "In-house Lawyer (4-7y)", 4, 7, 10, 16, None, None),
            ("Commerce & Industry", "In-house Lawyer (8y+)", 8, None, 13, 45, None, None),
            ("Commerce & Industry", "Legal Counsel non-qualified (0-3y)", 0, 3, 7, 10, None, None),
            ("Commerce & Industry", "Legal Counsel non-qualified (4-7y)", 4, 7, 8, 13, None, None),
            ("Commerce & Industry", "Legal Counsel non-qualified (8y+)", 8, None, 10, 16, None, None),
            ("Commerce & Industry", "Contract Manager (0-3y)", 0, 3, 6, 9, None, None),
            ("Commerce & Industry", "Contract Manager (4-7y)", 4, 7, 6, 8, None, None),
            ("Commerce & Industry", "Contract Manager (8y+)", 8, None, 8, 12, None, None),
            ("Financial Services", "Legal Counsel (0-3y)", 0, 3, 10, 15, 5000, 10000),
            ("Financial Services", "Legal Counsel (4-7y)", 4, 7, 15, 22, 5000, 10000),
            ("Financial Services", "Legal Counsel (8y+)", 8, None, 15, 50, 5000, 10000),
            ("Financial Services", "Compliance Officer (0-3y)", 0, 3, 6, 9, 2000, 5100),
            ("Financial Services", "Compliance Officer (4-8y)", 4, 8, 10, 20, 2000, 5100),
            ("Financial Services", "Compliance Officer (8-15y)", 8, 15, 15, 50, 2000, 5100),
            ("Private Practice", "Associate Lawyer (0-3y)", 0, 3, 10, 15, None, None),
            ("Private Practice", "Associate Lawyer (4-7y)", 4, 7, 12, 23, None, None),
            ("Private Practice", "Associate Lawyer (8y+)", 8, None, 15, 30, None, None),
            ("Private Practice", "Paralegal (0-3y)", 0, 3, 5, 7, 2500, 5500),
            ("Private Practice", "Paralegal (4-7y)", 4, 7, 5, 8, 2500, 5500),
            ("Private Practice", "Paralegal (8y+)", 8, None, 7, 10, 2500, 5500),
        ],
    },

    # ========================================================================
    {
        "slug": "manufacturing",
        "icon": "building",
        "name": "Manufacturing",
        "salary_increase_pct": 55,
        "confidence_pct": 61,
        "mobility_pct": 50,
        "expected_pay_bump_low": 10,
        "expected_pay_bump_high": 20,
        "expected_pay_bump_note": "Mobility/automotive: 10–15%. Semiconductor: 10–20% with key candidates seeing 15–20%. Energy & infrastructure: 15–20%, sometimes 20–40% for engineers with rare skills.",
        "top_demand": [
            "Managing Director (Country Manager)",
            "Sales Manager",
            "Project Manager",
        ],
        "trend_summary": "Mobility/auto faces external pressure (tariff uncertainty, China competition), driving cautious hiring but strong demand for SDV/AI-manufacturing talent. Semiconductor sector growing strongly with government subsidies. Energy & infrastructure sees rapid expansion in data centres, BESS, and energy trading.",
        "trend_east": "Mobility/auto: Cautious hiring volumes but salary increases robust (10–15%). SDV and AI-manufacturing specialists in demand. Semiconductor: Government-backed growth driving 10–20% raises with key engineers seeing 15–20%. Energy & infrastructure: Data centres and BESS booming; 15–20% increases in 2025, more expected. Some companies hiring without Japanese language requirements.",
        "trend_west": "Tariff uncertainty caused hiring freezes in some sectors, but weak yen drove foreign-investment-led hiring in construction. E-commerce/supply chain in high demand. Severe shortage of mechanical/electrical maintenance engineers and QA. Highly skilled foreign candidates being actively recruited. Salary gains for top engineers reached 20–40% in 2025.",
        "roles_east": [
            ("Chemical", "Sales Executive / Engineer", None, None, 6, 10, None, None),
            ("Chemical", "Application Engineer", None, None, 7, 13, None, None),
            ("Chemical", "Sales & Marketing Manager", None, None, 9, 15, None, None),
            ("Chemical", "R&D Manager", None, None, 10, 15, None, None),
            ("Chemical", "Product Manager", None, None, 8, 12, None, None),
            ("Chemical", "Business Development Manager", None, None, 12, 18, None, None),
            ("Chemical", "Sales & Marketing Director", None, None, 16, 25, None, None),
            ("Chemical", "R&D Director", None, None, 15, 25, None, None),
            ("Chemical", "President / CEO", None, None, 20, 40, None, None),
            ("Energy & Infrastructure", "Project Manager", None, None, 10, 15, None, None),
            ("Energy & Infrastructure", "Commissioning Engineer", None, None, 7, 12, None, None),
            ("Energy & Infrastructure", "O&M Manager", None, None, 9, 14, None, None),
            ("Energy & Infrastructure", "Architectural Project Manager", None, None, 9, 15, None, None),
            ("Energy & Infrastructure", "MEP Design Manager", None, None, 10, 15, None, None),
            ("Energy & Infrastructure", "Construction Manager", None, None, 8, 13, None, None),
            ("Energy & Infrastructure", "Business Development Manager", None, None, 9, 12, None, None),
            ("Energy & Infrastructure", "Sales Director", None, None, 10, 15, None, None),
            ("Energy & Infrastructure", "Project Development Director", None, None, 10, 15, None, None),
            ("Energy & Infrastructure", "Marketing Manager", None, None, 8, 12, None, None),
            ("Energy & Infrastructure", "Construction Director", None, None, 14, 20, None, None),
            ("Energy & Infrastructure", "Business Development Director", None, None, 13, 16, None, None),
            ("Energy & Infrastructure", "President / CEO", None, None, 18, 30, None, None),
            ("Industrial Engineering", "Field Service Manager / Director", None, None, 14, 17, None, None),
            ("Industrial Engineering", "Automation Engineer", None, None, 10, 15, None, None),
            ("Industrial Engineering", "Application / Design Engineer", None, None, 10, 15, None, None),
            ("Industrial Engineering", "Engineering Manager / Director", None, None, 15, 20, None, None),
            ("Industrial Engineering", "Project Manager", None, None, 10, 15, None, None),
            ("Industrial Sales & Marketing", "Sales Manager / Director", None, None, 18, 25, None, None),
            ("Industrial Sales & Marketing", "Product Marketing Manager", None, None, 12, 15, None, None),
            ("Industrial Sales & Marketing", "Country Manager / President / CEO", None, None, 25, 35, None, None),
            ("Industrial Sales & Marketing", "Field Marketing Manager", None, None, 12, 20, None, None),
            ("Industrial Sales & Marketing", "Marketing Manager / Director", None, None, 15, 20, None, None),
            ("Mobility Engineering", "Application / Design Engineer (Mechanical)", None, None, 6, 12, None, None),
            ("Mobility Engineering", "Application / Design Engineer (Electronics)", None, None, 8, 13, None, None),
            ("Mobility Engineering", "Engineering Manager", None, None, 10, 16, None, None),
            ("Mobility Engineering", "Project / Program Manager", None, None, 8, 15, None, None),
            ("Mobility Engineering", "Engineering Director / VP", None, None, 15, 35, None, None),
            ("Mobility Sales & Marketing", "Sales Executive / Associate", None, None, 5, 8, None, None),
            ("Mobility Sales & Marketing", "Account Manager / Sales Engineer", None, None, 8.5, 12, None, None),
            ("Mobility Sales & Marketing", "Sales Manager", None, None, 9, 15, None, None),
            ("Mobility Sales & Marketing", "Business Development Manager", None, None, 9, 15, None, None),
            ("Mobility Sales & Marketing", "Sales Director", None, None, 13, 25, None, None),
            ("Mobility Sales & Marketing", "Country Manager / Managing Director", None, None, 17, 40, None, None),
            ("Semiconductor", "Process Engineer", None, None, 8, 13, None, None),
            ("Semiconductor", "Field Service Engineer", None, None, 7, 10, None, None),
            ("Semiconductor", "Design Engineer", None, None, 6, 13, None, None),
            ("Semiconductor", "Sales / Business Development Manager", None, None, 10, 18, None, None),
            ("Semiconductor", "Field Application Engineer", None, None, 7, 15, None, None),
            ("Semiconductor", "Service Manager", None, None, 12, 17, None, None),
            ("Semiconductor", "Sales Director", None, None, 18, 30, None, None),
            ("Semiconductor", "Project Manager / Program Manager", None, None, 10, 15, None, None),
            ("Semiconductor", "Marketing Manager", None, None, 10, 15, None, None),
            ("Semiconductor", "Marketing Director", None, None, 15, 20, None, None),
            ("Semiconductor", "President / CEO", None, None, 20, 55, None, None),
        ],
        "roles_west": [
            ("Industrial", "President / CEO", None, None, 16, 30, None, None),
            ("Industrial", "Sales Director", None, None, 12, 18, None, None),
            ("Industrial", "Sales Manager", None, None, 9, 13, None, None),
            ("Industrial", "Marketing Manager", None, None, 9, 13, None, None),
            ("Industrial", "Application Engineer", None, None, 8, 14, None, None),
            ("Industrial", "Process Engineer / Manager", None, None, 9, 15, None, None),
            ("Industrial", "R&D Engineer", None, None, 8, 15, None, None),
            ("Industrial", "Project Manager", None, None, 8, 12, None, None),
            ("Industrial", "Design Engineer", None, None, 7, 10, None, None),
        ],
    },

    # ========================================================================
    {
        "slug": "tech-sales-marketing",
        "icon": "briefcase",
        "name": "Tech Sales & Marketing",
        "salary_increase_pct": 54,
        "confidence_pct": 66,
        "mobility_pct": 47,
        "expected_pay_bump_low": 15,
        "expected_pay_bump_high": 25,
        "expected_pay_bump_note": "Average 15–20% for job changers in 2025; up to 25% in specific fields. Foreign firms offering attractive USD-based RSU packages. E-commerce hiring junior talent under 30 aggressively.",
        "top_demand": [
            "Head of Sales",
            "Digital Marketing Manager",
            "Country Manager",
        ],
        "trend_summary": "AI is restructuring tech sales and marketing roles. Large corporations focus on AI transformations; mid-sized companies increase hiring of account managers and executives. E-commerce remains a hot growth area with active hiring for junior talent. Foreign firms offering USD-based RSU compensation is increasingly common.",
        "trend_east": "Restructuring continues as AI adoption shifts roles. Average 15–25% salary increases for job changers. Hunter sales account executives and performance marketing managers in high demand. Some e-commerce roles don't require Japanese. Female leadership promotion is gaining attention. Companies without remote-work options are losing top candidates.",
        "trend_west": "Kansai is digitalising fast as consumers shift to mobile and cashless. Strong demand for SAP engineers, product managers, cybersecurity specialists. Bilingual technical leaders see the largest premiums.",
        "roles_east": [
            ("Digital & Online", "Country Manager", None, None, 25, 50, 6800, 14000),
            ("Digital & Online", "E-commerce Director", None, None, 15, 30, 5100, 12000),
            ("Digital & Online", "E-commerce Manager", None, None, 8, 12, 3800, 8100),
            ("Digital & Online", "E-commerce Specialist", None, None, 5, 8, 2500, 5100),
            ("Digital & Online", "Digital Marketing Director", None, None, 15, 30, 5100, 12000),
            ("Digital & Online", "Digital Marketing Manager", None, None, 9, 18, 3800, 8100),
            ("Digital & Online", "Digital Marketing Specialist", None, None, 5, 9, 2500, 5100),
            ("Digital & Online", "Digital / Ad Tech Sales Manager", None, None, 8, 18, 3800, 9300),
            ("Digital & Online", "Digital Product Manager", None, None, 10, 17, 3800, 8100),
            ("Digital & Online", "Advertising Account Manager", None, None, 8, 12, 3800, 8100),
            ("Digital & Online", "Advertising Account Director", None, None, 12, 18, 5100, 12000),
            ("Digital & Online", "Graphic / Web / UI / UX Designer", None, None, 6, 15, 3800, 8100),
            ("Digital & Online", "Art Director", None, None, 6, 15, 3800, 9300),
            ("Digital & Online", "Creative Director", None, None, 15, 23, 3800, 9300),
            ("Digital & Online", "Social Media Manager", None, None, 8, 13, 2500, 7100),
            ("IT Infrastructure & Services", "Country Manager", None, None, 25, 60, 6800, 14000),
            ("IT Infrastructure & Services", "Marketing Director", None, None, 15, 25, 5100, 12000),
            ("IT Infrastructure & Services", "Marketing Manager", None, None, 10, 20, 3800, 8100),
            ("IT Infrastructure & Services", "Marketing Specialist", None, None, 5, 10, 2500, 5100),
            ("IT Infrastructure & Services", "Channel Sales Manager", None, None, 10, 25, 3800, 8100),
            ("IT Infrastructure & Services", "Product Marketing Manager", None, None, 10, 25, 3800, 8100),
            ("IT Infrastructure & Services", "Sales Account Manager", None, None, 10, 30, 3800, 8100),
            ("IT Infrastructure & Services", "Sales Development Representative", None, None, 5, 13, 2500, 5100),
            ("IT Software", "Country Manager", None, None, 30, 60, 6800, 14000),
            ("IT Software", "Sales Director", None, None, 20, 40, 5100, 12000),
            ("IT Software", "Sales Manager", None, None, 15, 25, 3800, 9300),
            ("IT Software", "Marketing Director", None, None, 15, 25, 5100, 12000),
            ("IT Software", "Marketing Manager", None, None, 10, 15, 3800, 8100),
            ("IT Software", "Marketing Specialist", None, None, 6, 10, 2500, 5100),
            ("IT Software", "Channel Sales Manager", None, None, 15, 25, 3800, 8100),
            ("IT Software", "Customer Success Manager", None, None, 10, 20, 3200, 7700),
            ("IT Software", "Product Marketing Manager", None, None, 15, 25, 3800, 8100),
            ("IT Software", "Sales Account Manager", None, None, 10, 20, 3800, 8100),
            ("IT Software", "Sales Development Representative", None, None, 7, 15, 2500, 5100),
        ],
        "roles_west": [
            ("Digital & Online", "Branch Manager", None, None, 10, 15, None, None),
            ("Digital & Online", "Sales Manager", None, None, 9.2, 15, None, None),
            ("Digital & Online", "Sales Account Manager", None, None, 7, 11, None, None),
            ("Digital & Online", "Sales Executive", None, None, 5, 10, None, None),
            ("Digital & Online", "Account Manager", None, None, 8, 13, None, None),
            ("Digital & Online", "Senior Manager", None, None, 10, 15, None, None),
            ("Digital & Online", "Sales Director", None, None, 13, 20, None, None),
            ("Digital & Online", "Marketing Specialist", None, None, 8, 10, 1700, 3100),
            ("Digital & Online", "Customer Service Manager", None, None, 7, 13, None, None),
        ],
    },

    # ========================================================================
    {
        "slug": "supply-chain-procurement",
        "icon": "package",
        "name": "Supply Chain, Procurement & Operations",
        "salary_increase_pct": 57,
        "confidence_pct": 62,
        "mobility_pct": 48,
        "expected_pay_bump_low": 5,
        "expected_pay_bump_high": 15,
        "expected_pay_bump_note": "Salary growth varies widely by role and digital skillset. Top performers in trade compliance / customs and automation see premium offers; routine logistics roles closer to 5%.",
        "top_demand": [
            "SCM Planning (IBP / Demand / Supply Planning)",
            "QA/QC, Factory, & EHS",
            "Procurement",
        ],
        "trend_summary": "Logistics disruptions, driver shortages, and tariff volatility continue impacting hiring. Companies adopting flexible hiring (experienced seniors + recent graduates). Trade compliance and customs procedures expertise is increasingly valuable. Conversion of temp/contract workers to permanent continues.",
        "trend_east": "Demand growing for SCM (inbound logistics, demand/supply planning), QA/QC, EHS, and procurement. Digital transformation specialists with automation skills have an advantage. Soft skills like team management critical alongside technical knowledge.",
        "roles_east": [
            ("Procurement", "Procurement Director / Head of Procurement", None, None, 15, 25, None, None),
            ("Procurement", "Procurement Manager (Direct)", None, None, 10, 17, None, None),
            ("Procurement", "Procurement Manager (Indirect)", None, None, 10, 17, None, None),
            ("Procurement", "Procurement Senior Specialist / Lead", None, None, 7, 10, None, None),
            ("Procurement", "Purchaser / Buyer", None, None, 5.5, 8, None, None),
            ("Supply Chain & Logistics", "SCM Director / Head of SCM", None, None, 15, 40, None, None),
            ("Supply Chain & Logistics", "Operations Director", None, None, 15, 20, None, None),
            ("Supply Chain & Logistics", "Supply Chain Manager", None, None, 10, 17, None, None),
            ("Supply Chain & Logistics", "Call Centre Manager", None, None, 7, 15, None, None),
            ("Supply Chain & Logistics", "Customer Service Manager", None, None, 9, 14, None, None),
            ("Supply Chain & Logistics", "Customer Service Specialist", None, None, 5, 8, None, None),
            ("Supply Chain & Logistics", "EHS Director", None, None, 15, 22, None, None),
            ("Supply Chain & Logistics", "EHS Manager", None, None, 10, 15, None, None),
            ("Supply Chain & Logistics", "EHS Specialist", None, None, 6, 9, None, None),
            ("Supply Chain & Logistics", "Factory / Plant Manager", None, None, 20, 30, None, None),
            ("Supply Chain & Logistics", "Logistics Director", None, None, 15, 20, None, None),
            ("Supply Chain & Logistics", "Logistics Manager", None, None, 9, 15, None, None),
            ("Supply Chain & Logistics", "Logistics Specialist", None, None, 5, 8, None, None),
            ("Supply Chain & Logistics", "Country Manager (Logistics / Freight)", None, None, 15, 40, None, None),
            ("Supply Chain & Logistics", "Sales Manager (Logistics / Freight)", None, None, 9, 15, None, None),
            ("Supply Chain & Logistics", "Operations Manager (Logistics / Freight)", None, None, 9, 15, None, None),
            ("Supply Chain & Logistics", "Sales Specialist (Logistics / Freight)", None, None, 5, 8, None, None),
            ("Supply Chain & Logistics", "Production Manager", None, None, 12, 17, None, None),
            ("Supply Chain & Logistics", "Production Specialist", None, None, 8, 11, None, None),
            ("Supply Chain & Logistics", "SCM Project Manager", None, None, 9, 17, None, None),
            ("Supply Chain & Logistics", "QA/QC Director", None, None, 15, 30, None, None),
            ("Supply Chain & Logistics", "QA/QC Manager", None, None, 12, 16, None, None),
            ("Supply Chain & Logistics", "QA/QC Specialist", None, None, 8, 11, None, None),
            ("Supply Chain & Logistics", "Warehouse Manager", None, None, 9, 14, None, None),
            ("Supply Chain & Logistics", "Planning Manager", None, None, 10, 16, None, None),
            ("Supply Chain & Logistics", "Planning Senior Specialist / Lead", None, None, 7, 12, None, None),
            ("Supply Chain & Logistics", "Planning Specialist", None, None, 6.5, 9, None, None),
        ],
        "roles_west": [
            ("Industrial", "Facilities Engineer (Non-Data Centre)", None, None, 7, 10, None, None),
            ("Industrial", "Facilities Engineer / Manager", None, None, 8, 17, None, None),
            ("Industrial", "Factory / Plant Manager", None, None, 10, 16, None, None),
            ("Procurement", "Procurement Director", None, None, 15, 25, None, None),
            ("Procurement", "Procurement Manager", None, None, 10, 15, None, None),
            ("Procurement", "Buyer / Procurement Staff", None, None, 6, 10, 1400, 2800),
            ("Supply Chain & Logistics", "Operations Director", None, None, 15, 30, None, None),
            ("Supply Chain & Logistics", "Logistics Manager", None, None, 8, 15, None, None),
            ("Supply Chain & Logistics", "Customer Service Manager", None, None, 8, 12, None, None),
            ("Supply Chain & Logistics", "EHS Director", None, None, 12, 20, None, None),
            ("Supply Chain & Logistics", "EHS Manager", None, None, 10, 16, None, None),
            ("Supply Chain & Logistics", "Production Control Manager", None, None, 8, 16, None, None),
            ("Supply Chain & Logistics", "Supply Chain Manager", None, None, 8, 13, None, None),
            ("Supply Chain & Logistics", "Warehouse Manager", None, None, 6, 15, None, None),
            ("Supply Chain & Logistics", "Planner", None, None, 8, 12, None, None),
        ],
    },

    # ========================================================================
    {
        "slug": "tech-transformation",
        "icon": "cpu",
        "name": "Tech & Transformation",
        "salary_increase_pct": 50,
        "confidence_pct": 67,
        "mobility_pct": 47,
        "expected_pay_bump_low": 10,
        "expected_pay_bump_high": 30,
        "expected_pay_bump_note": "Vendor sector 10–20%, up to 30% for critical roles. Product IT 8–12%. Fintech 15–20%, up to 30% for rare skills. Consulting 10–20%. Junior West Japan tech: 10–30%.",
        "top_demand": [
            "Cloud Architect / Engineer",
            "Data Scientist / AI Engineer",
            "Cybersecurity Specialist",
        ],
        "trend_summary": "Tech vendor sector picked up in late 2025 with growing demand for presales engineers, project managers, AI specialists, and solution architects. Cybersecurity engineers, ERP specialists, and IT managers are critically short. Bilingual professionals with cloud security / AI governance / DevOps expertise command 15–20% raises, sometimes 30% for rare skills.",
        "trend_east": "Mid-to-senior level demand growing fastest. Bilingual technical talent for client-facing roles commands premium offers. Fintech sees wage inflation and labour shortages. Consulting firms hiring aggressively for cloud, data analytics, AI, and ERP. Career growth opportunities increasingly important alongside salary.",
        "trend_west": "Kansai catching up on digitalisation creates growth opportunities. Strong demand for SAP engineers, product managers, cybersecurity specialists, AI. Japanese language proficiency increasingly required alongside technical skills. Bilingual tech leaders see the largest premiums; junior employees often see 10–30% raises.",
        "roles_east": [
            ("General", "IT Director", None, None, 10, 20, 4000, 8000),
            ("General", "IT Manager", None, None, 7, 12, 4000, 6000),
            ("General", "Chief Technology Officer", None, None, 12, 25, 8400, 26000),
            ("General", "Infrastructure Manager", None, None, 10, 15, 7000, 9500),
            ("General", "Infrastructure Engineer", None, None, 7, 12, 6000, 9000),
            ("General", "Network Engineer", None, None, 8, 13, 4000, 9000),
            ("General", "Database Administrator", None, None, 7, 13, 7000, 9000),
            ("General", "Systems Engineer", None, None, 6, 10, 4000, 7000),
            ("General", "Systems Administrator", None, None, 7, 11, 5350, 7500),
            ("General", "Application Manager", None, None, 10, 16, 3500, 11000),
            ("General", "Project Manager", None, None, 7, 15, 3000, 7000),
            ("General", "Project Manager (Senior)", None, None, 9, 14, 2500, 6000),
            ("General", "Program Manager", None, None, 15, 20, 3500, 5000),
            ("General", "Business Analyst", None, None, 9, 15, 3000, 7000),
            ("General", "Business Partner", None, None, 12, 16, 3500, 11000),
            ("General", "Enterprise Architect", None, None, 10, 15, 3500, 9000),
            ("General", "Solution Architect", None, None, 12, 20, 3500, 11000),
            ("General", "Data Analyst", None, None, 7, 14, 2000, 4500),
            ("General", "Data Scientist", None, None, 8, 16, 3000, 6000),
            ("General", "Data Centre Engineer", None, None, 10, 12, 2400, 9800),
            ("General", "CRM Engineer", None, None, 8, 15, 2500, 6300),
            ("General", "E-commerce Engineer", None, None, 6, 10, 4000, 9000),
            ("General", "End User Support", None, None, 6, 9, 2000, 5000),
            ("General", "ERP Engineer", None, None, 8, 13, 2500, 6300),
            ("General", "ERP Consultant", None, None, 7, 13, 3000, 12000),
            ("General", "POS Engineer", None, None, 7, 10, 3500, 6000),
            ("General", "Security Engineer", None, None, 8, 20, 5000, 12000),
            ("General", "Security Specialist", None, None, 9, 15, 3000, 8000),
            ("General", "Service Delivery Manager", None, None, 10, 15, 4000, 7000),
            ("General", "Service Delivery Director", None, None, 16, 25, 8000, 12000),
            ("General", "Back-End Developer", None, None, 7, 14, 2000, 11000),
            ("General", "Front-End Developer", None, None, 7, 14, 2000, 8000),
            ("General", "Web Application Developer", None, None, 8, 14, 2400, 11000),
            ("General", "Web Developer", None, None, 8, 14, 2400, 11000),
            ("General", "Web Designer", None, None, 7, 9, 2100, 4500),
            ("General", "Web Director", None, None, 7, 12, 2000, 6300),
            ("General", "Mobile Developer", None, None, 8, 14, 2000, 8000),
            ("General", "DevOps Engineer", None, None, 8, 15, 2000, 11500),
            ("General", "Site Reliability Engineer", None, None, 8, 15, 2400, 11500),
            ("General", "Software Developer", None, None, 6, 17, 4000, 7000),
            ("General", "Machine Learning Engineer", None, None, 7, 16, 3500, 6000),
            ("General", "Cloud Engineer", None, None, 10, 16, 5000, 14000),
            ("General", "Customer Success Manager", None, None, 10, 20, 2000, 4000),
            ("General", "Field Application Engineer", None, None, 9, 12, 2000, 6300),
            ("General", "IoT Consultant", None, None, 7, 15, 5000, 14000),
            ("General", "IT Consultant", None, None, 9, 20, 4000, 7000),
            ("General", "Pre-sales Engineer", None, None, 10, 18, 2400, 11000),
            ("General", "Post-sales Engineer", None, None, 7, 14, 3500, 11000),
            ("General", "Product Manager", None, None, 9, 20, 3000, 5000),
            ("General", "Quality Assurance Engineer", None, None, 5, 12, 2500, 8000),
            ("General", "RPA Consultant", None, None, 7, 16, 3000, 9400),
            ("General", "Technical Consultant", None, None, 8, 15, 2400, 9400),
            ("General", "Technical Support Engineer", None, None, 8, 13, 4000, 8000),
            ("General", "Telephony Engineer", None, None, 9, 14, 5000, 11000),
            ("General", "UI / UX Designer", None, None, 8, 12, 3000, 6000),
            ("General", "Game Producer", None, None, 7, 12, 4000, 9000),
            ("General", "Graphic Designer", None, None, 6, 9, 4500, 7000),
            ("General", "Localisation Engineer", None, None, 6, 8.5, 3000, 7000),
            ("General", "Project Coordinator", None, None, 6, 8, 2000, 4000),
            ("Banking", "Chief Information Officer", None, None, 30, 50, 8400, 26000),
            ("Banking", "Head of Development", None, None, 25, 33, 8400, 26000),
            ("Banking", "Head of Infrastructure", None, None, 25, 33, 9000, 16000),
            ("Banking", "Head of Support", None, None, 25, 33, 8000, 12500),
            ("Banking", "Information Security Officer", None, None, 17, 30, 5000, 15000),
            ("Banking", "Systems Manager", None, None, 16, 22, 8000, 9500),
            ("Banking", "Developer", None, None, 12, 28, 2000, 11000),
            ("Banking", "Database Administrator", None, None, 11, 15, 5000, 9500),
            ("Banking", "Application Support", None, None, 13, 18, 1800, 7000),
            ("Banking", "Business Analyst", None, None, 13, 18, 3000, 6000),
            ("Banking", "Incident Manager", None, None, 13, 18, 4000, 10000),
            ("Banking", "Network Engineer", None, None, 13, 19, 4000, 13000),
            ("Banking", "Project Manager", None, None, 13, 19, 5000, 8000),
            ("Banking", "Systems Administrator", None, None, 11, 15, 6000, 10500),
            ("Non-Banking", "Chief Information Officer", None, None, 22, 35, 8400, 26000),
            ("Non-Banking", "IT Director", None, None, 14, 25, 3000, 6000),
            ("Non-Banking", "Head of Development", None, None, 17, 20, 8400, 26000),
            ("Non-Banking", "IT Manager", None, None, 9, 14, 3000, 5000),
            ("Non-Banking", "Architect", None, None, 12, 18, 3500, 11000),
            ("Non-Banking", "Information Security", None, None, 9, 18, 5000, 15000),
            ("Non-Banking", "Cloud Engineer", None, None, 10, 16, 5000, 14000),
            ("Non-Banking", "Data Scientist", None, None, 10, 16, 3000, 6000),
            ("Non-Banking", "Data Analyst", None, None, 10, 14, 2500, 4500),
            ("Non-Banking", "Database Administrator", None, None, 10, 12, 5000, 9500),
            ("Non-Banking", "Developer", None, None, 8, 12, 2000, 11000),
            ("Non-Banking", "DevOps Engineer", None, None, 10, 16, 2000, 12000),
            ("Non-Banking", "Application Support", None, None, 8, 11, 1800, 7000),
            ("Non-Banking", "Business Analyst", None, None, 10, 12, 2500, 4500),
            ("Non-Banking", "Business Process Re-engineering", None, None, 11, 14, 3000, 9400),
            ("Non-Banking", "Infrastructure Manager", None, None, 12, 14, 6500, 9500),
            ("Non-Banking", "Program Manager", None, None, 12, 17, 3000, 6000),
            ("Non-Banking", "Project Management Officer", None, None, 9, 12, 2200, 4000),
            ("Non-Banking", "Project Manager", None, None, 10, 16, 3000, 5000),
            ("Non-Banking", "Systems Analyst", None, None, 10, 12, 5000, 9000),
            ("Non-Banking", "UI / UX Designer", None, None, 9, 12, 3000, 5500),
            ("Non-Banking", "Web Developer", None, None, 9, 12, 2000, 8500),
            ("Non-Banking", "UNIX Systems Administrator", None, None, 10, 12, 6000, 9500),
            ("Non-Banking", "Wintel Systems Administrator", None, None, 8, 10, 7500, 9000),
        ],
        "roles_west": [
            ("General", "Chief Technology Officer", None, None, 18, 45, None, None),
            ("General", "IT Director", None, None, 13, 25, None, None),
            ("General", "IT Manager", None, None, 7, 15.5, None, None),
            ("General", "Enterprise Technical Sale", None, None, 8, 30, None, None),
            ("General", "Technical Sales", None, None, 5, 17, None, None),
            ("General", "Technical Account Manager", None, None, 7, 18, None, None),
            ("General", "Pre Sales Engineer", None, None, 8, 18, None, None),
            ("General", "Post Sales Engineer", None, None, 7, 16, None, None),
            ("General", "Project Manager", None, None, 7, 18, 2500, 5200),
            ("General", "Service Delivery Manager", None, None, 10, 17, 4000, 6500),
            ("General", "Infrastructure Engineer", None, None, 5.5, 14, 2200, 4600),
            ("General", "Infrastructure Manager", None, None, 8, 16, 4000, 6000),
            ("General", "Network Engineer", None, None, 5, 12, 2200, 5000),
            ("General", "Database Administrator", None, None, 5, 14, 3200, 5500),
            ("General", "System Engineer", None, None, 5, 12, 2200, 3600),
            ("General", "DevOps Engineer", None, None, 6, 14.5, 3500, 7500),
            ("General", "Site Reliability Engineer", None, None, 6, 16, 3200, 7000),
            ("General", "Security Engineer", None, None, 6, 16, 3200, 9000),
            ("General", "Service Delivery Director", None, None, 16, 27, 5000, 10000),
            ("General", "Technical Support Engineer", None, None, 6, 15, 2200, 5000),
            ("General", "Desktop Support / Help Desk", None, None, 4, 10, 2000, 3200),
            ("Banking", "Information Security Officer", None, None, 12, 25, 4300, 10000),
            ("Banking", "Head of Infrastructure", None, None, 12, 20, 5800, 10000),
            ("Banking", "Head of Support", None, None, 9, 18, 5000, 8100),
            ("Banking", "Incident Manager", None, None, 10, 18, 4000, 7100),
            ("Banking", "Application Support", None, None, 8, 16, 2000, 3500),
            ("Banking", "Project Manager", None, None, 13, 19, 2200, 5500),
            ("Banking", "Systems Administrator", None, None, 8, 15, 4000, 6000),
            ("Banking", "Database Administrator", None, None, 5, 14, 3000, 5500),
            ("Banking", "Network Engineer", None, None, 6, 13, 2200, 5500),
            ("Non-Banking", "Information Security", None, None, 5, 16, 3000, 7000),
            ("Non-Banking", "Infrastructure Manager", None, None, 9, 18, 4000, 6000),
            ("Non-Banking", "Program Manager", None, None, 10, 18, 3000, 7500),
            ("Non-Banking", "Project Management Officer", None, None, 6, 18, 2500, 6500),
            ("Non-Banking", "Project Manager", None, None, 7, 18, 2200, 5500),
            ("Non-Banking", "DevOps Engineer", None, None, 6, 14.5, 3000, 7100),
        ],
    },
]


def get_sector(slug: str) -> dict | None:
    return next((s for s in SECTORS if s["slug"] == slug), None)
